### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmos-multisig-ui#101]
This repository is missing a LICENSE. Given that it has been developed for the Interchain Foundation in the past, I assume Apache 2 is the appropriate choice. At least from Confio's perfective it is.

I'd like to ask the contributors of this repo to confirm they are happy with that

- [x] @webmaster128 (Confio GmbH)
- [x] @abefernan (Confio GmbH)
- [x] @msteiner96 (Confio GmbH)
- [x] @samepant
- [ ] @klk1236
- [x] @nooomski
- [ ] @okwme

**Comment by nooomski** [comment]
Works for me! Just know I don't represent the owners of the org (ICF) anymore. I think none of the people listed do. But I doubt it matters.

**Comment by webmaster128** [comment]
> Just know I don't represent the owners of the org (ICF) anymore. I think none of the people listed do. But I doubt it matters.

Thank you. Yes, you are right. I was mostly thinking about the ICF as the funder of the initial work. I know their licensing requirement is usually Apache 2. So it should be in their interest to make this explicit now.

**Comment by nooomski** [comment]
I'm inquiring directly with the ICF team and will let you know.

**Comment by zhongxinhua91** [comment]
Yes ok with Apache 2
