### ISSUE TITLE
Allow chosing a different denom in MsgSend

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmos-multisig-ui#147]
While `state.chain.displayDenom` is a great default, it should be possible to send different denoms as well.

For the staking messages we don't need such a flexibility because there is only one staking denom.

**Comment by abefernan** [comment]
Some questions:
- Should we support only 1 coin or an arbitrary amount of coins?
- Should the coins be on a dropdown list loaded from the chain-registry assetlist? Or should the user enter the data?
- Allow user to input fractional digits, or do we use microamount always?
- What about ibc/ coins (to MsgSend them to different accounts on the same network)

**Comment by webmaster128** [comment]
1. I'd say one coin is enough. Otherwise it gets complicated in the UI and a user can also use multiple MsgSend.
2. The asset list is a great start. Let's have a dropdown for the list and allow custom denoms. (With this we can also avoid the need for the `displayDenom` for MsgSend and can rename this to staking denom later on.)
3. All the dropdown values can be entered in decimal notation. Custom denoms need to be in the base denom.
4. They should be allowed to enter as custom denoms in their raw form (ibc/ABABABA...)
