### ISSUE TITLE
Failed to fetch when try live website

### ISSUE THREAD

**Issue by hoangphuc36006** [cosmos/cosmos-multisig-ui#153]
hello , can u fix it ? 
![image](https://github.com/cosmos/cosmos-multisig-ui/assets/40860346/3e7ed715-786a-452f-ad2d-ac4510c9836c)

**Comment by abefernan** [comment]
That account has pubkey of type `tendermint/PubKeySecp256k1` instead of `tendermint/PubKeyMultisigThreshold`, maybe you're using the wrong address?
