### ISSUE TITLE
Error on connect keplr

### ISSUE THREAD

**Issue by kaisbaccour** [cosmos/cosmos-multisig-ui#179]
I am not able to connect Keplr to sign the tx. Tried to delete the cache didn't solve it, tried from a different tab doesn't work either.
Tx link: https://cosmos-multisig-ui-kohl.vercel.app/nois/nois13t0dg6503xafyclj8q9e7kpvwaq0dsrq0g8j6a/transaction/380290585468076631 

<img width="1415" alt="Screenshot_2023-11-02_at_16 17 19" src="https://github.com/cosmos/cosmos-multisig-ui/assets/31540265/4b977097-6b13-4765-9321-d13593c8690d">

**Comment by abefernan** [comment]
Hi! Did you add Nois to Keplr by clicking on the "Manage chain visibility" option on Keplr's top left menu?

**Comment by webmaster128** [comment]
The last error "There is o chain info for nois-1" is coming from Keplr. It means that Nois is not installed properly in Keplr. I talked with @kaisbaccour and it seems like this was indeed the problem. Closing here.
