### ISSUE TITLE
Delegation amount keeps resetting to 0

### ISSUE THREAD

**Issue by willyogo** [cosmos/cosmos-multisig-ui#180]
gm frens! currently unable to delegate ATOM because after clicking 'Create Transaction', the Amount gets reset to 0.

Here's a screen recording encountering the bug:

https://github.com/cosmos/cosmos-multisig-ui/assets/26232238/7bc13eaf-bd4d-4849-baf3-a39410f2433b

**Comment by abefernan** [comment]
`ATOM` uses 6 decimals for pretty printing `uatom`. It should work if you use 6 decimals at most instead of 7. But we should improve form validation

**Comment by webmaster128** [comment]
`Decimal.fromUserInput` throws if the fractional part has more digits than supported. But it seems like the exception is turned into a 0 value here:

```ts
    const microCoin = (() => {
      try {
        return macroCoinToMicroCoin({ denom, amount }, chain.assets);
      } catch {
        return { denom, amount: "0" };
      }
    })();
```
