### ISSUE TITLE
Setup linter

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmos-multisig-ui#19]
At the moment there is no tooling for linting and code formatting, right?

Yesterday I tried to setup eslint + prettier, which is a combination I'm very happy with for other projects. It was not easy to configure due to JSX/React and a bunch of other things. Also there are some unmaintained files in the folder that probably should be excluded.

Before I invest more work in this, I'd like to check if this is something we want here and if eslint is fine for you? This setup can easily be extended by a TypeScript plugin, such that we are prepared for a TS migration.

**Comment by samepant** [comment]
This would be great!

I've been using my local prettier setup, but would be happy to have eslint and prettier set up in the repo, now that there will be multiple contributors. 

[Next.js has some eslint tooling](https://nextjs.org/docs/basic-features/eslint) that may make things easier to setup, but we may need to upgrade a version.

**Comment by webmaster128** [comment]
[next lint](https://nextjs.org/docs/basic-features/eslint) looks nice and it's probably not hard to migrate there when starting with an eslint setup. But you need Next.js version 11 for that.
