### ISSUE TITLE
Transaction Page not loading

### ISSUE THREAD

**Issue by rbpollock** [cosmos/cosmos-multisig-ui#196]
After creating a transaction, exiting the flow (or having one signer sign) and then navigating to the full transaction url, the route /[chainregistryname]/[account]/transaction/[transactionid] returns an error with the route, preventing other signers from signing.
![Screenshot 2024-01-28 172322](https://github.com/cosmos/cosmos-multisig-ui/assets/43445728/b57f61e6-da4e-481f-8b8c-caac40fc5125)

`Invalid href '//secret1qr445x2x5gjcfpd74a6feva762awfmgzlw7ams' passed to next/router in page: '/[chainName]/[address]/transaction/[transactionID]'. Repeated forward-slashes (//) or backslashes \ are not valid in the href.`

to view: https://cosmos-multisig-ui-kohl.vercel.app/secretnetwork/secret1qr445x2x5gjcfpd74a6feva762awfmgzlw7ams/transaction/388200927909118551

**Comment by abefernan** [comment]
I will fix the console and Multisig errors, but the users should able to sign either way, the connect Keplr/Ledger button appears below that view, doesn't it?
