### ISSUE TITLE
Feature Request: Add msg authz grant and revoke

### ISSUE THREAD

**Issue by puneet2019** [cosmos/cosmos-multisig-ui#206]
till #129 is ready and can allow encoding of arbitrary types, we can have authz grant and revoke, so multisig participants can use UI for certain msg types by giving authz to any address ( for a day or so) and optionally revoking it if the address is corrupted.

**Comment by abefernan** [comment]
It looks like CosmJS does not yet support signing those with ledgers https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/modules/authz/aminomessages.ts

**Comment by abefernan** [comment]
Not yet solved, but added to #99
