### ISSUE TITLE
code 4 error

### ISSUE THREAD

**Issue by surrenderoz** [cosmos/cosmos-multisig-ui#209]
Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (387787), sequence (0) and chain-id (froopyland_100-1): unauthorized

**Comment by surrenderoz** [comment]
I'm trying to broadcast transaction on dymension chain but I got error with code 4 

 signature verification failed; please verify account number (387787), sequence (0) and chain-id (froopyland_100-1): unauthorized

**Comment by webmaster128** [comment]
I don't know how Dymension works but it seems to use some sort of incompatible signing mode. Not much we can do here.
