### ISSUE TITLE
[bug] Can't create multisig, accounts are not seen as present but they are

### ISSUE THREAD

**Issue by kopeboy** [cosmos/cosmos-multisig-ui#212]
_Error
An account needs to be present on chain before creating a transaction. Send some tokens to the address first._

I tested with both
`osmo19nt2pfvcrpsgasm2rv2mpalsd52hq69t675zzf`
`osmo1y3r9yazgfyanpefqej2czulqctcnp76lp750cr`
and
`juno1y3r9yazgfyanpefqej2czulqctcnp76llhyyfd`
`juno19nt2pfvcrpsgasm2rv2mpalsd52hq69tyhyfn8`
which are existing accounts.

**Comment by abefernan** [comment]
Does that happen on the Multisig view (`/juno/<multisig-address>`) or on the transaction view (`/juno/<multisig-address>/transaction/<transaction-id>`)?

Are those addresses the members of the multisig, or the multisig itself?

**Comment by nsonanh** [comment]
I have the same problem for dHealth: https://multisig.confio.run/dhealth

Error
An account needs to be present on chain before creating a transaction. Send some tokens to the address first.

I tested with existing, functioning accounts and this error always appear

**Comment by kopeboy** [comment]
> Can't create multisig

That happens on the /create @abefernan !

**Comment by abefernan** [comment]
I'm guessing @kopeboy the pairs of addresses you shared are the members of the multisig, right?

@nsonanh @kopeboy you need to send some tokens to the multisig address (the one in the URL) before being able to use it with this tool. I'm aware this is confusing and a better UX will come soon.

If you also get a toast error on the bottom right of the page, you can copy the full error so I can better debug it

**Comment by nsonanh** [comment]
@abefernan you mean the address on the url bar here?
![image](https://github.com/cosmos/cosmos-multisig-ui/assets/15029492/f29f6f62-6a5e-42ff-b076-0b49696ed283)

**Comment by abefernan** [comment]
@nsonanh yes, that is the multisig address. After you send some tokens there, the view should work

**Comment by abefernan** [comment]
Closing after improving the view in #214.
