### ISSUE TITLE
Unclear how to share signing link

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmos-multisig-ui#26]
Right now the user sees this when a transaction was composed and sigened:

![Screenshot 2022-01-28 at 15 34 36](https://user-images.githubusercontent.com/2603011/151565575-6097bee0-bf5e-48c2-a2f2-7c0b2ea1a870.png)

At this point it is unclear what needs to be done in order to let other users sign. Also it does not work great if the transaction composer is not in the signer set.

In order to clarify this in the UI, I propose the following screens:
1. Compose transaction
2. Confirm of compose, show signing link in UI. Composer can copy link or sign if in the signer set.
3. Signing screen

**Comment by nooomski** [comment]
Definitely in favor of this idea!
Would also suggest adding a warning if you're not in the signer set.
