### ISSUE TITLE
Feature: Import existing transaction

### ISSUE THREAD

**Issue by msteiner96** [cosmos/cosmos-multisig-ui#33]
As of now, it's possible to create new transactions. Besides that we should add a button "Import Transaction" which let's the user importing the JSON String of an existing transaction. Otherwise it's only possible to sign simple transfers.

E.g. in JUNO they need more advanced transactions to delegate stuff etc. 

A simple textbox to import pre-formatted JSON should be enough.

**Comment by samepant** [comment]
This would be really nice.

Let's track this in #29 since it will require changes to Cosmjs and this app to support this feature.
