### ISSUE TITLE
Iterate between available endpoints if RPC node is not available

### ISSUE THREAD

**Issue by nooomski** [cosmos/cosmos-multisig-ui#44]
Using Comdex as an example, the console printed an error that the the node was not available. I would suggest putting all RPC endpoints in an array, catching any error, and iterating over the list until there is a successful connection.

On failure at end of array, inform the user that none of the listed RPC endpoints are, available instead of the generic "failed to fetch" message.

**Comment by webmaster128** [comment]
This should not be hard to implement since we already have this:

```ts
      const nodeAddress = getNodeFromArray(chainData.apis.rpc);

    // ...

      // test client connection
      const client = await StargateClient.connect(nodeAddress);
      await client.getHeight();
```

So we can just make the successful height query a requirement inside of `getNodeFromArray`.
