### ISSUE TITLE
NEXT_PUBLIC_MULTICHAIN can't be set to false

### ISSUE THREAD

**Issue by msteiner96** [cosmos/cosmos-multisig-ui#48]
NEXT_PUBLIC_MULTICHAIN can't be set to `false`, since it's always interpreted as a string. This means that `if (process.env.NEXT_PUBLIC_MULTICHAIN )` is always true.

**Comment by samepant** [comment]
Nice catch, fixed with 19c01d31f877a127c6617b65968cdc84387125fc
