### ISSUE TITLE
Add support for create-vesting-account

### ISSUE THREAD

**Issue by nooomski** [cosmos/cosmos-multisig-ui#49]
Would be cool if there was an option to create a vesting account. A few things to consider:

- To create a vesting account, the address needs to not have been initialised on-chain already (i.e. never received a balance)
- To create a vesting account, some tokens need to be transferred in that `create-vesting-account` Tx
- There are two ways to do vesting:
  - Delayed vesting: all tokens unlock at once at a specified time (the most common usage)
  - Continuous: all tokens unlock continuously until a specific time
- The [spec](https://docs.cosmos.network/v0.42/modules/auth/05_vesting.html) seems to be out of date, as it is currently possible to create new vesting accounts (just tested it on theta testnet)

This is primarily aimed at funding organisations like the ICF.

If you'd like you can experiment with this on CLI on the Theta testnet using 'gaiad tx vesting create-vesting-account [receiving address] [amount] [unix epoch time] --chain-id theta-testnet-001 --node http://rpc.sentry-01.theta-testnet.polypore.xyz:26657 --from [sending key] --delayed`. Please ping me if you need testnet tokens.

**Comment by webmaster128** [comment]
This relates to #29, https://github.com/cosmos/cosmjs/issues/1074 and https://github.com/cosmos/cosmjs/pull/1083. Basically I don't see a way to import arbitrary JSON messages as this JSON is not standardized but specific to the Go implementation. This means you need to add support for messages one by one.

https://github.com/cosmos/cosmjs/issues/1074 is a blocker for sure. Are there other relevant message types?

Then the question is how to compose the message. If we create a dedicates UI for the message type, no JSON import is needed. If the accounts should be generated from Go CLI (e.g. gaiad), we need an impoter like https://github.com/cosmos/cosmjs/pull/1083.

**Comment by webmaster128** [comment]
Blocked by https://github.com/cosmos/cosmjs/issues/1115

**Comment by webmaster128** [comment]
The Amino JSON signing for MsgCreateVestingAccount is supported in CosmJS 0.29.x and Cosmos SDK 0.46.

@nooomski do we have a Cosmos SDK 0.46 testnet? If so we can update https://github.com/cosmos/cosmos-multisig-ui/pull/54 and get this feature in.

**Comment by nooomski** [comment]
Sorry for the delay here @webmaster128 . We don't have one yet afaik, but Cosmos Hub will launch a devnet end of august / early september and will update the longer running testnet end of september.
