### ISSUE TITLE
Add testnets from the registry

### ISSUE THREAD

**Issue by nooomski** [cosmos/cosmos-multisig-ui#55]
@samepant any chance we could include testnets as well for testing this tool? My accountant would appreciate it if I could not use real ATOMs ;)

I've updated my chain registry repo to include testnets, I think you can probably copy a bunch: https://github.com/nooomski/registry-ui

**Comment by webmaster128** [comment]
Testnets are in this sub-folder. I guess the files have the same structure as the mainnets.
https://github.com/cosmos/chain-registry/tree/master/testnets
