### ISSUE TITLE
theta-testnet-001 - not supporting

### ISSUE THREAD

**Issue by arunsybex** [cosmos/cosmos-multisig-ui#63]
@webmaster128   https://rpc.sentry-01.theta-testnet.polypore.xyz   this testnet not working!

![image](https://user-images.githubusercontent.com/20275068/172619547-32ae76e8-d5e1-4cfd-bf7f-2c41f56bd822.png)

**Comment by nooomski** [comment]
Yeah, closing in favor of #60
