### ISSUE TITLE
Provenance `denom exponent` is incorrect value

### ISSUE THREAD

**Issue by minxylynx** [cosmos/cosmos-multisig-ui#76]
It's currently showing as `6`, when it should be `9`. I hope this is the place to have it corrected.

**Comment by webmaster128** [comment]
I can confirm the issue:

<img width="983" alt="Bildschirmfoto 2022-08-12 um 18 23 24" src="https://user-images.githubusercontent.com/2603011/184401099-14a58554-8832-4a34-ae24-7c6f032059a5.png">

**Comment by webmaster128** [comment]
Should be fixed in https://github.com/cosmos/cosmos-multisig-ui/pull/77

**Comment by nooomski** [comment]
@minxylynx closing this for now. Please reopen if the issue persists. Thank you!

**Comment by nooomski** [comment]
Lol, sorry my bad, thought I had 77 open but was looking at a different closed PR.
