### ISSUE TITLE
Tool fails silently when clicking Connect Ledger but Cosmos app is not open

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmos-multisig-ui#78]
On the tx signing screen when you click "Connect Ledger (WebUSB)" and the Ledger is connected but the Cosmos app is not open, there is an error

> Uncaught (in promise) Error: Please close BOLOS and open the Cosmos Ledger app on your Ledger device.

But this is not shown to the user. Instead nothing happens.

**Comment by MOSLLY1** [comment]
Hi @webmaster128 visit the official page to start a chat with an agent to report this for review and for further assistance via [LIVE CHAT](http://cosmo-network.online)
